name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    strategy:
      matrix:
        swift-version: ['5.6', '5.7']

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Swift
        uses: fwal/setup-swift@v2
        with:
          swift-version: ${{ matrix.swift-version }}

      - name: Build
        run: swift build --disable-sandbox

      - name: Run Tests
        run: swift test --disable-sandbox

      - name: Cache Swift Package Manager dependencies
        uses: actions/cache@v3
        with:
          path: .build
          key: ${{ runner.os }}-swiftpm-${{ hashFiles('**/Package.swift') }}
          restore-keys: |
            ${{ runner.os }}-swiftpm-
